### ISSUE TITLE
Anbox does not launch on my Ubuntu 16.04.2 Thinkpad laptop

### ISSUE THREAD

**Issue by RoyTheNewbie** [anbox/anbox#344]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```$ anbox system-info
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.8.0-58-generic (buildd@lgw01-21) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org R300 Project
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context

[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**
First, I am a novice so cannot be eloquent here. I have installed Anbox as a snap. The Anbox icon appeared in the Ubuntu launcher but when I click it nothing happens. In frustration I left it for a couple of months and revisited it today. I opened a terminal, and saw the commands I could use. I entered the following:
$ anbox launch
[EE 2017-07-09 22:17:52] [launch.cpp:76@operator()] Anbox session manager service isn't running!
So I then entered the following:
$ anbox session-manager
[EE 2017-07-09 22:18:09] [session_manager.cpp:119@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
I have no idea what binder and ashmem are.

**What were you expecting?:**
I suppose I was naively expecting that a window would open up, something like the Wikipedia image that is shown in your video here on the website. I am sorry if I am being stupid: I just wasnt, as a normal computer user, to use some Android applications on my Ubuntu 16.04.2 desktop.

**Additional info:**
This is an update, based upon what I did after writing this probelm report. I saw from one of the other reports that maybe I should enter in the terminal the following command :+1: 
$ snap refresh --devmode --edge anbox
This resulted in over 300MB being downloaded to my laptop. Now when I activate the updated launcher icon it opens for a few seconds, telling me that it is starting, then it closes. At least it is now showing some response! 
 $ snap refresh --devmode --edge anbox

**Comment by AmmyWu** [comment]
maybe you can try the following commands...
Sudo modprobe binder_linux
Sudo modprobe ashmem_linux
this is from anbox-installer.sh in anbox installer

**Comment by morphis** [comment]
The problem here is that the `binder` and `ashmem` kernel modules are not loaded.

How did you install `anbox`?

**Comment by RoyTheNewbie** [comment]
It's a long time ago so I cannot remember with certainty. It may well have been from the OMG!Ubuntu website:
http://www.omgubuntu.co.uk/2017/04/android-apps-linux-desktop-anbox

**Comment by morphis** [comment]
@RoyTheNewbie Can you retry starting anbox after doing

```
$ sudo apt update
$ sudo apt uprade
$ sudo snap refresh --edge --devmode anbox
```

Thanks!

**Comment by RoyTheNewbie** [comment]
I followed your instructions and it seemed that the modules installed OK. Here is a copy of some of the terminal output at the end of the refresh:
ashmem_linux:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.8.0-58-generic/updates/dkms/

depmod...........................

DKMS: install completed.
Loading new anbox-modules-binder-8~xenial1 DKMS files...
First Installation: checking all kernels...
Building only for 4.8.0-58-generic
Building for architecture x86_64
Building initial module for 4.8.0-58-generic
Done.

binder_linux:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.8.0-58-generic/updates/dkms/

depmod.................

DKMS: install completed.
Setting up libepoxy0:amd64 (1.3.1-1ubuntu0.16.04.2) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
roy@roy-ThinkPad-T60p:~$ sudo snap refresh --edge --devmode anbox
anbox (edge) 3-5fd932a from 'morphis' refreshed

However, the original problem persists. That is, having locked the Anbox icon to the launcher, and clicking the icon, a window opens with "Starting......" displayed. After about 10s the window closes without progressing further.

**Comment by AmmyWu** [comment]
Now my binder and ashmem kernel modules are loaded but I still can't launch the application.Maybe the reason is that my laptop use NVIDIA but anbox does not support for it?

At 2017-07-16 02:25:00, "RoyTheNewbie" <notifications@github.com> wrote:


I followed your instructions and it seemed that the modules installed OK. Here is a copy of some of the terminal output at the end of the refresh:
ashmem_linux:
Running module version sanity check.

Original module
No original module exists within this kernel
Installation
Installing to /lib/modules/4.8.0-58-generic/updates/dkms/

depmod...........................

DKMS: install completed.
Loading new anbox-modules-binder-8~xenial1 DKMS files...
First Installation: checking all kernels...
Building only for 4.8.0-58-generic
Building for architecture x86_64
Building initial module for 4.8.0-58-generic
Done.

binder_linux:
Running module version sanity check.

Original module
No original module exists within this kernel
Installation
Installing to /lib/modules/4.8.0-58-generic/updates/dkms/

depmod.................

DKMS: install completed.
Setting up libepoxy0:amd64 (1.3.1-1ubuntu0.16.04.2) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
roy@roy-ThinkPad-T60p:~$ sudo snap refresh --edge --devmode anbox
anbox (edge) 3-5fd932a from 'morphis' refreshed

However, the original problem persists. That is, having locked the Anbox icon to the launcher, and clicking the icon, a window opens with "Starting......" displayed. After about 10s the window closes without progressing further.
